import Foundation
import AppKit
import DuoPasteCore

/// 已知的"非用户原始操作"类型，应跳过。
/// 参考 nspasteboard.org 约定 + Apple 自家的 transient 标记。
private let skipMarkerTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",          // 1Password 的私有标记
    "Pasteboard generator type",          // 老式应用偶尔用
]

@MainActor
public final class PasteboardWatcher {
    public typealias Callback = @MainActor (CapturedPasteboard) -> Void

    private let pasteboard: NSPasteboard
    private let pollInterval: TimeInterval
    /// debounce 窗口（纳秒）。changeCount 跳变后等这么久没新跳变才真正 capture。
    ///
    /// 用途：合并 app 自己的连续多次剪贴板写入。已知场景：
    /// - **CleanShot**：截图保存时先写本地缓存路径，iCloud Drive 同步完成后改写
    ///   iCloud 路径——一次截图两次 changeCount 跳变，原本会变成两条 file item
    /// - 富文本 app（Notes / Mail）在写 .rtf + .html + .string 时可能分多次 setString
    ///
    /// 0 = 关闭 debounce 立即 capture（测试 / 调试注入）。默认 500ms：
    /// - 远低于人眼反应（200-300ms）+ panel 打开动画时间，用户完全察觉不到
    /// - 比 CleanShot 观察到的 iCloud 同步延迟（~200ms）留充足 buffer
    private let debounceNs: Int64
    private var lastChangeCount: Int
    /// 进入 debounce 等待时记录的触发时刻。0 = 当前没 pending capture。
    /// 每次 changeCount 跳变都重置为 `now + debounceNs`，直到稳定一整个窗口才触发
    private var pendingDeadlineNs: Int64 = 0
    private var timer: Timer?
    private let onCapture: Callback
    /// 仅 RTF 路径用于解码前 raw-size 守门，避免 50MB RTF source 被 NSAttributedString 同步
    /// 解析后才走到 CaptureService 的 text byte cap。raw RTF 字节 > 该上限时跳过 decode，
    /// 把 raw RTF 直接作为兜底 .rtf 文本返回 —— CaptureService 后续 byte-cap 会拦下。
    /// 默认值匹配 Config.CaptureLimits.maxTextBytes 默认（512 * 1024）；AppDelegate 注入实际配置。
    private let maxRawRTFBytes: Int

    public init(
        pasteboard: NSPasteboard = .general,
        pollInterval: TimeInterval = 0.2,
        debounceMs: Int = 500,
        maxRawRTFBytes: Int = 512 * 1024,
        onCapture: @escaping Callback
    ) {
        self.pasteboard = pasteboard
        self.pollInterval = pollInterval
        self.debounceNs = Int64(max(0, debounceMs)) * 1_000_000
        self.maxRawRTFBytes = maxRawRTFBytes
        self.lastChangeCount = pasteboard.changeCount
        self.onCapture = onCapture
    }

    /// 由"自己写回剪贴板"的代码在写完后调用，把内部 lastChangeCount 推到当前值，
    /// 让接下来一次或多次 tick 不会把自己的写入误当作用户复制。
    ///
    /// 同时清空 `pendingDeadlineNs`：write back 路径完成后任何 pending debounce 都失效，
    /// 否则会在 deadline 到期时把自己刚 suppress 的写回当成 capture 重新触发 callback。
    ///
    /// **注意**：若 paste-back 发生时刚好处在某次真实复制的 debounce 窗口内，那条真实
    /// 复制会被本方法连同 pending 一起丢弃 —— 调用方应当在写回 pasteboard **之前**先调
    /// `flushPendingIfAny()` 把真实复制提交掉，再调本方法做 self-write 抑制。
    public func suppressUpToCurrent() {
        lastChangeCount = pasteboard.changeCount
        pendingDeadlineNs = 0
    }

    /// 在 paste-back 写回 pasteboard **之前**调：若 debounce 窗口里有 pending 的真实
    /// 复制，立刻 capture 一次（此刻 pasteboard 还是用户复制的原始内容），让那条真实
    /// 复制不会被随后的 suppressUpToCurrent 静默丢弃。
    ///
    /// 覆盖两条路径：
    /// 1. `pendingDeadlineNs > 0`：tick 已经观察到 changeCount 变化、正在 debounce
    /// 2. `pasteboard.changeCount != lastChangeCount`：用户在两次 tick 间隔（≤200ms）
    ///    刚复制完就立刻按 Enter，tick 还没轮到、`pendingDeadlineNs` 还是 0。此时
    ///    必须也 flush，否则随后的 Copyback.write 会覆盖未观察到的真实复制
    ///
    /// 没有任何变化 → no-op。
    public func flushPendingIfAny() {
        let cc = pasteboard.changeCount
        if cc != lastChangeCount {
            // 未观察到的真实复制 —— 先 stamp lastChangeCount 让 capture 不再被 tick 重复抓
            lastChangeCount = cc
            pendingDeadlineNs = 0
            capture()
            return
        }
        guard pendingDeadlineNs > 0 else { return }
        pendingDeadlineNs = 0
        capture()
    }

    public func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let cc = pasteboard.changeCount
        if cc != lastChangeCount {
            lastChangeCount = cc
            if debounceNs > 0 {
                // 进入或重置 debounce 等待窗口。这一 tick 不 capture——等下次 tick
                // 看 cc 是否还稳定（用户没继续写）才触发。app 在窗口内再次写剪贴板
                // （如 CleanShot 100ms 后改写 iCloud 路径）→ 重新走到这里 → deadline 刷新
                pendingDeadlineNs = Clock.nowNs() + debounceNs
                return
            }
            // 显式关 debounce → 立即 capture（测试 / 调试可用，零回归）
            capture()
            return
        }
        // cc 稳定（这一 tick 没人写）。看 pending 窗口是否已过期 → 触发 capture
        guard pendingDeadlineNs > 0,
              Clock.nowNs() >= pendingDeadlineNs
        else { return }
        pendingDeadlineNs = 0
        capture()
    }

    /// 真正读 pasteboard 提取内容并回调。从 tick() 拆出来——debounce 路径在 deadline
    /// 到期时调；零 debounce 路径在 changeCount 跳变时立刻调。
    /// 注意：skipMarkerTypes 检测放在这里（不是 changeCount 跳变时刻），因为
    /// debounce 窗口内 app 可能还没写完所有 type marker
    private func capture() {
        let capturedAtNs = Clock.nowNs()

        // 跳过特殊标记类型
        if let types = pasteboard.types {
            for t in types where skipMarkerTypes.contains(t.rawValue) {
                return
            }
        }

        guard let captured = extract(capturedAtNs: capturedAtNs) else {
            return
        }
        // 诊断：可疑 capture 把 NSPasteboard types 全打出来。三种触发：
        // (1) ≤8 字符的短文本——「Paste.app 跳过但我们 capture」的不对称定位
        // (2) RTF kind——常见误抓自 Telegram/Notes/Mail 这类 styled-text app 的后台写入
        // (3) HTML kind——本应被 looksLikeWebViewHTML 降级，真走到 .html 的都是值得记
        //     的反例（原生富文本 app 或我们漏掉的 web view 写入形态）
        // 用途：识别漏配的 type marker（应进 skipMarkerTypes），或定位 frontmost 时序错位
        let shouldLog: Bool
        if let t = captured.text, t.count <= 8, captured.kind == .text {
            shouldLog = true
        } else if captured.kind == .rtf {
            shouldLog = true
        } else if captured.kind == .html {
            shouldLog = true
        } else {
            shouldLog = false
        }
        if shouldLog {
            let types = pasteboard.types?.map(\.rawValue).joined(separator: ",") ?? "(nil)"
            let textLen = captured.text?.count ?? 0
            let prevSlice = (captured.text ?? "").prefix(40)
            fputs("capture suspect kind=\(captured.kind.rawValue) bundle=\(captured.sourceAppBundleID ?? "?") name=\(captured.sourceAppName ?? "?") len=\(textLen) types=[\(types)] preview=\(String(prevSlice).debugDescription)\n", stderr)
        }
        onCapture(captured)
    }

    private func extract(capturedAtNs: Int64) -> CapturedPasteboard? {
        let frontApp = NSWorkspace.shared.frontmostApplication
        // 注：早期版本会在 frontApp.pid == self.pid 时直接 return nil，理由是"搜索框
        // Cmd+C 不污染历史"。但实测用户更常的诉求是把搜索框里的串作为新剪贴板项入库
        // （剪贴板管理器本质就是"复制就该被记录"）。self-pid 跳过的副作用：那次
        // changeCount 被吃掉再也不补，搜索结果永远 0 条。已取消跳过；pasteBack 路径
        // 自己用 suppressUpToCurrent 保护，不依赖 self-pid 过滤。
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName

        // 1) 文件 URL
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }.joined(separator: "\n")
            return CapturedPasteboard(
                kind: .file,
                text: paths,
                fileName: urls.count == 1 ? urls[0].lastPathComponent : nil,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 2) 图片：优先 PNG，再 TIFF
        if let data = pasteboard.data(forType: .png) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "png",
                blobMime: "image/png",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }
        if let data = pasteboard.data(forType: .tiff) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "tiff",
                blobMime: "image/tiff",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 3) RTF
        if let rtf = pasteboard.string(forType: .rtf) {
            // RTF 降级：剪贴板历史里展示 `{\rtf1\ansi\ansicpg... \cocoartf...}` 这种 raw
            // markup 完全没意义——搜索命中不了、preview 噪声大、bundle name 也只是 host
            // app（Codex/Claude Desktop/Notes/Mail 等）。代价：失去"按原样 paste 回带样
            // 式"——但本仓库定位是剪贴板历史检索，不是富文本中转站；况且 Copyback 已经
            // 在多数情况下双写 rtf+string，对端粘贴体验由对端 app 决定。
            //
            // 三层降级：
            // (a) pasteboard 自己写了 .string → 直接用
            // (b) 只写了 .rtf（Notes/Mail 部分场景）→ 本地解 RTF markup 拿 attributed.string
            // (c) 解析失败/全空白/raw 太大 → 才存 raw rtf 当兜底（CaptureService 字节守门后续拦下）
            if let plain = pasteboard.string(forType: .string),
               !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            {
                return CapturedPasteboard(
                    kind: .text,
                    text: plain,
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    capturedAtNs: capturedAtNs
                )
            }
            // raw RTF 已经超过 text cap → 跳过 NSAttributedString 解析，避免在 @MainActor
            // 轮询路径上同步分配巨大 attributed string。decoded plain ≤ raw rtf，所以这种 case
            // 解出来也大概率仍超 cap，让 CaptureService 拦 raw 即可
            if rtf.utf8.count <= maxRawRTFBytes,
               let plain = Self.decodeRTFToPlain(rtf),
               !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            {
                return CapturedPasteboard(
                    kind: .text,
                    text: plain,
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    capturedAtNs: capturedAtNs
                )
            }
            return CapturedPasteboard(
                kind: .rtf,
                text: rtf,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 4) HTML
        if let html = pasteboard.string(forType: .html) {
            // web view selection 降级：WebKit / Chromium 系（浏览器 + Electron + Codex /
            // ChatGPT / Claude Desktop 等）写 HTML 时前面会塞 <meta charset='utf-8'>，
            // 内容是带 inline style + data-* 属性的一坨 markup——对剪贴板管理器毫无用处。
            // 此时如果 .string 也有非空 plain text，优先用 plain，丢 markup。
            if looksLikeWebViewHTML(html),
               let plain = pasteboard.string(forType: .string),
               !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            {
                return CapturedPasteboard(
                    kind: .text,
                    text: plain,
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    capturedAtNs: capturedAtNs
                )
            }
            return CapturedPasteboard(
                kind: .html,
                text: html,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 5) URL（web URL，区别于 fileURL）
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first, !url.isFileURL
        {
            return CapturedPasteboard(
                kind: .url,
                text: url.absoluteString,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 6) 纯文本——trim 后判空，过滤掉单空格 / 纯换行 / 纯 tab 之类的伪复制。
        // 实测来源：Zed Vim mode 在空白字符上 yank、LSP 命令副作用、空选择 Cmd+C 等。
        // 不直接 .isEmpty 判断会让这些 1-字节空白条目刷进列表（preview 完全空，无信息量）。
        if let s = pasteboard.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return CapturedPasteboard(
                kind: .text,
                text: s,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        return nil
    }

    /// 用 NSAttributedString 把 RTF source 解成纯文本。失败返回 nil，调用方走兜底。
    private static func decodeRTFToPlain(_ rtf: String) -> String? {
        guard let data = rtf.data(using: .utf8),
              let attr = try? NSAttributedString(
                data: data,
                options: [.documentType: NSAttributedString.DocumentType.rtf],
                documentAttributes: nil
              )
        else { return nil }
        return attr.string
    }
}
