import Foundation
import AppKit
import DuoPasteCore

/// 已知的"非用户原始操作"类型，应跳过。
/// 参考 nspasteboard.org 约定 + Apple 自家的 transient 标记。
private let skipMarkerTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",          // 1Password 的私有标记
    "Pasteboard generator type",          // 老式应用偶尔用
]

@MainActor
public final class PasteboardWatcher {
    public typealias Callback = @MainActor (CapturedPasteboard) -> Void

    private let pasteboard: NSPasteboard
    private let pollInterval: TimeInterval
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: Callback

    public init(
        pasteboard: NSPasteboard = .general,
        pollInterval: TimeInterval = 0.2,
        onCapture: @escaping Callback
    ) {
        self.pasteboard = pasteboard
        self.pollInterval = pollInterval
        self.lastChangeCount = pasteboard.changeCount
        self.onCapture = onCapture
    }

    /// 由"自己写回剪贴板"的代码在写完后调用，把内部 lastChangeCount 推到当前值，
    /// 让接下来一次或多次 tick 不会把自己的写入误当作用户复制。
    public func suppressUpToCurrent() {
        lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc

        let capturedAtNs = Clock.nowNs()

        // 跳过特殊标记类型
        if let types = pasteboard.types {
            for t in types where skipMarkerTypes.contains(t.rawValue) {
                return
            }
        }

        guard let captured = extract(capturedAtNs: capturedAtNs) else {
            return
        }
        onCapture(captured)
    }

    private func extract(capturedAtNs: Int64) -> CapturedPasteboard? {
        let frontApp = NSWorkspace.shared.frontmostApplication
        // 自己是前台时（搜索面板打开期间）任何剪贴板变化都不入库，
        // 否则用户在搜索框里选中文本一 Cmd+C 就会污染历史
        if frontApp?.processIdentifier == ProcessInfo.processInfo.processIdentifier {
            return nil
        }
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName

        // 1) 文件 URL
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }.joined(separator: "\n")
            return CapturedPasteboard(
                kind: .file,
                text: paths,
                fileName: urls.count == 1 ? urls[0].lastPathComponent : nil,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 2) 图片：优先 PNG，再 TIFF
        if let data = pasteboard.data(forType: .png) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "png",
                blobMime: "image/png",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }
        if let data = pasteboard.data(forType: .tiff) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "tiff",
                blobMime: "image/tiff",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 3) RTF
        if let rtf = pasteboard.string(forType: .rtf) {
            return CapturedPasteboard(
                kind: .rtf,
                text: rtf,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 4) HTML
        if let html = pasteboard.string(forType: .html) {
            return CapturedPasteboard(
                kind: .html,
                text: html,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 5) URL（web URL，区别于 fileURL）
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first, !url.isFileURL
        {
            return CapturedPasteboard(
                kind: .url,
                text: url.absoluteString,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 6) 纯文本
        if let s = pasteboard.string(forType: .string), !s.isEmpty {
            return CapturedPasteboard(
                kind: .text,
                text: s,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        return nil
    }
}
