import Foundation
import AppKit
import DuoPasteCore

/// 已知的"非用户原始操作"类型，应跳过。
/// 参考 nspasteboard.org 约定 + Apple 自家的 transient 标记。
private let skipMarkerTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",          // 1Password 的私有标记
    "Pasteboard generator type",          // 老式应用偶尔用
]

@MainActor
public final class PasteboardWatcher {
    public typealias Callback = @MainActor (CapturedPasteboard) -> Void

    private let pasteboard: NSPasteboard
    private let pollInterval: TimeInterval
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: Callback

    public init(
        pasteboard: NSPasteboard = .general,
        pollInterval: TimeInterval = 0.2,
        onCapture: @escaping Callback
    ) {
        self.pasteboard = pasteboard
        self.pollInterval = pollInterval
        self.lastChangeCount = pasteboard.changeCount
        self.onCapture = onCapture
    }

    /// 由"自己写回剪贴板"的代码在写完后调用，把内部 lastChangeCount 推到当前值，
    /// 让接下来一次或多次 tick 不会把自己的写入误当作用户复制。
    public func suppressUpToCurrent() {
        lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc

        let capturedAtNs = Clock.nowNs()

        // 跳过特殊标记类型
        if let types = pasteboard.types {
            for t in types where skipMarkerTypes.contains(t.rawValue) {
                return
            }
        }

        guard let captured = extract(capturedAtNs: capturedAtNs) else {
            return
        }
        // 诊断：可疑 capture 把 NSPasteboard types 全打出来。三种触发：
        // (1) ≤8 字符的短文本——「Paste.app 跳过但我们 capture」的不对称定位
        // (2) RTF kind——常见误抓自 Telegram/Notes/Mail 这类 styled-text app 的后台写入
        // (3) HTML kind——本应被 looksLikeWebViewHTML 降级，真走到 .html 的都是值得记
        //     的反例（原生富文本 app 或我们漏掉的 web view 写入形态）
        // 用途：识别漏配的 type marker（应进 skipMarkerTypes），或定位 frontmost 时序错位
        let shouldLog: Bool
        if let t = captured.text, t.count <= 8, captured.kind == .text {
            shouldLog = true
        } else if captured.kind == .rtf {
            shouldLog = true
        } else if captured.kind == .html {
            shouldLog = true
        } else {
            shouldLog = false
        }
        if shouldLog {
            let types = pasteboard.types?.map(\.rawValue).joined(separator: ",") ?? "(nil)"
            let textLen = captured.text?.count ?? 0
            let prevSlice = (captured.text ?? "").prefix(40)
            fputs("capture suspect kind=\(captured.kind.rawValue) bundle=\(captured.sourceAppBundleID ?? "?") name=\(captured.sourceAppName ?? "?") len=\(textLen) types=[\(types)] preview=\(String(prevSlice).debugDescription)\n", stderr)
        }
        onCapture(captured)
    }

    private func extract(capturedAtNs: Int64) -> CapturedPasteboard? {
        let frontApp = NSWorkspace.shared.frontmostApplication
        // 自己是前台时（搜索面板打开期间）任何剪贴板变化都不入库，
        // 否则用户在搜索框里选中文本一 Cmd+C 就会污染历史
        if frontApp?.processIdentifier == ProcessInfo.processInfo.processIdentifier {
            return nil
        }
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName

        // 1) 文件 URL
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }.joined(separator: "\n")
            return CapturedPasteboard(
                kind: .file,
                text: paths,
                fileName: urls.count == 1 ? urls[0].lastPathComponent : nil,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 2) 图片：优先 PNG，再 TIFF
        if let data = pasteboard.data(forType: .png) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "png",
                blobMime: "image/png",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }
        if let data = pasteboard.data(forType: .tiff) {
            return CapturedPasteboard(
                kind: .image,
                blob: data,
                blobExt: "tiff",
                blobMime: "image/tiff",
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 3) RTF
        if let rtf = pasteboard.string(forType: .rtf) {
            // RTF 降级：剪贴板历史里展示 `{\rtf1\ansi\ansicpg... \cocoartf...}` 这种 raw
            // markup 完全没意义——搜索命中不了、preview 噪声大、bundle name 也只是 host
            // app（Codex/Claude Desktop/Notes/Mail 等）。只要 .string 有非空 plain，优先
            // 用 plain 入 text 类。代价：失去"按原样 paste 回带样式"——但本仓库定位是
            // 剪贴板历史检索，不是富文本中转站；况且 Copyback 已经在多数情况下双写
            // rtf+string，对端粘贴体验由对端 app 决定。
            if let plain = pasteboard.string(forType: .string),
               !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            {
                return CapturedPasteboard(
                    kind: .text,
                    text: plain,
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    capturedAtNs: capturedAtNs
                )
            }
            return CapturedPasteboard(
                kind: .rtf,
                text: rtf,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 4) HTML
        if let html = pasteboard.string(forType: .html) {
            // web view selection 降级：WebKit / Chromium 系（浏览器 + Electron + Codex /
            // ChatGPT / Claude Desktop 等）写 HTML 时前面会塞 <meta charset='utf-8'>，
            // 内容是带 inline style + data-* 属性的一坨 markup——对剪贴板管理器毫无用处。
            // 此时如果 .string 也有非空 plain text，优先用 plain，丢 markup。
            if looksLikeWebViewHTML(html),
               let plain = pasteboard.string(forType: .string),
               !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            {
                return CapturedPasteboard(
                    kind: .text,
                    text: plain,
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    capturedAtNs: capturedAtNs
                )
            }
            return CapturedPasteboard(
                kind: .html,
                text: html,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 5) URL（web URL，区别于 fileURL）
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first, !url.isFileURL
        {
            return CapturedPasteboard(
                kind: .url,
                text: url.absoluteString,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        // 6) 纯文本——trim 后判空，过滤掉单空格 / 纯换行 / 纯 tab 之类的伪复制。
        // 实测来源：Zed Vim mode 在空白字符上 yank、LSP 命令副作用、空选择 Cmd+C 等。
        // 不直接 .isEmpty 判断会让这些 1-字节空白条目刷进列表（preview 完全空，无信息量）。
        if let s = pasteboard.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return CapturedPasteboard(
                kind: .text,
                text: s,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                capturedAtNs: capturedAtNs
            )
        }

        return nil
    }
}
